theme: jekyll-theme-minimal
title: GeorgiAna's homepage
description: Bookmark this to keep an eye on my project updates!

	<script> document.cookie = "session=test GDPR"; document.cookie = "favorite_task=collect Data"; function alertCookie() { alert(document.cookie); } </script>
<body> Bine ai venit la lab <button onclick="alertCookie()">Show cookies</button> </body>
